import fs from 'fs';
import path from 'path';

const docsDir = './website/docs';
const outputFile = './website/docs-data.js';

const files = {
  'welcome': 'index.md',
  'architecture': 'architecture.md',
  'dashboard': 'dashboard.md',
  'api-reference': 'api-reference.md',
  'providers-guide': 'providers-guide.md'
};

const docsData = {};

for (const [key, filename] of Object.entries(files)) {
  const filePath = path.join(docsDir, filename);
  if (fs.existsSync(filePath)) {
    docsData[key] = fs.readFileSync(filePath, 'utf8');
    console.log(`Loaded ${filename}`);
  } else {
    console.warn(`Warning: File ${filePath} not found`);
    docsData[key] = `# ${key}\nContent not found.`;
  }
}

const jsContent = `// Automatically generated by scripts/build-docs.js. Do not edit directly.
window.AURORA_DOCS = ${JSON.stringify(docsData, null, 2)};
`;

fs.writeFileSync(outputFile, jsContent, 'utf8');
console.log(`Successfully generated ${outputFile}`);
